name: Deploy to Gigalixir
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Git HTTPS push deploy
        uses: ilkka/git-https-push-action@v1.1.0
        with:
          remoteUrl: ${{ secrets.PUSH_REMOTE }}
          skipHooks: false
