name: Publish client to NPM
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.1.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - run: mix deps.get
      - run: mix wobbly.open_api_spec spec.json
      - name: Upload OpenAPI spec artifact
        uses: actions/upload-artifact@v1
        with:
          name: openapi_spec
          path: spec.json
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: actions/setup-java@v1
        with:
          java-version: "13.x"
          java-package: jre
      - name: Download OpenAPI spec artifact
        uses: actions/download-artifact@v1
        with:
          name: openapi_spec
      - name: Download OpenAPI generator
        run: npm install @openapitools/openapi-generator-cli -g
      - name: Generate TypeScript client
        run: npx openapi-generator generate -i openapi_spec/spec.json -g typescript-redux-query -o client/
      - working-directory: ./client
        run: |-
          echo -e "{
              \"name\": \"@wobbly/api-client\",
              \"version\": \"$(git describe --tags)\",
              \"main\": \"src/index.ts\",
              \"author\": {
                \"name\": \"wobbly\"
              },
              \"license\": \"GPL-3.0-or-later\",
              \"private\": false
            }" > package.json
      - run: npm publish
        working-directory: ./client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
